config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'home#index'
    get '/log_in', to: 'home#log_in'
    get '/auth/spotify', as: 'auth'
    get '/auth/spotify/callback', to: 'home#log_in'
    resources :clients, only: %I(new create)
  namespace :twilio do
      post 'messages', to: 'messages#create'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_one :user, dependent: :destroy
  validates :client_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :client
  
  def access_token_expired?
    (Time.now - updated_at) > 3300
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
  end

  def create
    @client = Client.create(client_params)
    session[:client_id] = client_params[:client_id]
    session[:client_secret] = client_params[:client_secret]
  end

  private

  def client_params
    params.require(:client).permit(:client_id, :client_secret)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @param = {
      client_id: session[:client_id],
      response_type: "code",
      scope: 'playlist-modify-public user-library-read user-library-modify',
      redirect_uri: "https://#{request.host}/auth/spotify/callback",
      show_dialog: true
    }
    @url = "https://accounts.spotify.com/authorize?"
  end

  def log_in
    param = {
      grant_type: "authorization_code",
      code: params[:code],
      redirect_uri: "https://#{request.host}/auth/spotify/callback",
      client_id: session[:client_id],
      client_secret: session[:client_secret]
    }

    resp = RestClient.post('https://accounts.spotify.com/api/token', param)
    json_resp = JSON.parse(resp)
    
    header = { Authorization: "Bearer #{json_resp["access_token"]}" }

    final_resp = RestClient.get('https://api.spotify.com/v1/me', header)

    user_params = JSON.parse(final_resp)

    spotify_user = RSpotify::User.new(
    {
      'id' => user_params['id'],
      'credentials' => {
        "token" => json_resp["access_token"],
        "refresh_token" => json_resp["refresh_token"]
      }
    })

    @user_id = spotify_user.id

    @credentials = spotify_user.credentials
    @user = User.find_by(user_id: @user_id)

    if @user
      @user.update(access_token: json_resp["access_token"], refresh_token: json_resp["refresh_token"])
    else
      @user = client.create_user(user_id: @user_id, access_token: json_resp["access_token"], refresh_token: json_resp["refresh_token"])
    end
  end

  def client
    Client.find_by(client_id: session[:client_id])
  end

end

app/controllers/twilio/messages_controller.rb
class Twilio::MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :setup_user, if: -> { params['Body'].split.first.eql? '#self' }
  before_action :set_user

  def create
    track_keyword = params['Body']
    if track_keyword.to_i == 0
      tracks = RSpotify::Track.search(track_keyword).first(3)
      message = "Following are the track suggestions-\n"
      tracks.each_with_index { |track, i| message += "#{i+1}. #{track.name} by #{track.artists.map(&:name).join(',')}\n" } 
      message += "Please type a number to add track in liked songs"
    else
      user_id = @user.user_id
      token = @user.access_token
      refresh_token = @user.refresh_token
      @user = RSpotify::User.new({
            'id' => user_id,
            'credentials' => {
              'token' => token,
              'refresh_token' => refresh_token
            }})

      track = RSpotify::Track.search(session[:track_keyword]).first(3)[track_keyword.to_i - 1]
      #If you want to add in playlist
        #track_uri = track.uri    
        #playlist.add_tracks!([track_uri])   
      #If you want to add in liked song
      @user.save_tracks!([track])
      message = "Track is added in liked songs successfully!!"
    end

    send_message message
    session[:track_keyword] = track_keyword
  end

  private

  def set_user
    @user = User.find_by(phone: params['From']) || User.first
    if @user.access_token_expired?
      request_body = {
        grant_type: 'refresh_token', 
        refresh_token: @user.refresh_token,
        client_id: @user.client.client_id,
        client_secret: @user.client.client_secret
      }
      response = RestClient.post('https://accounts.spotify.com/api/token', request_body)
      json_response = JSON.parse(response)
      @user.update(access_token: json_response["access_token"])
    end
  end

  def setup_user
    client = Client.where("client_id like ?", "#{params['Body'].split.last}%").first
    if client
      client.user.update_attribute(:phone, params['From'])
      message = "Your Spotify account is linked now!\nYou can now search and like the song"
      send_message message
    else
      message = "You have entered wrong ClientId\n Or you may have not registered first"
      send_message message
    end
  end

  def send_message message
    response = Twilio::TwiML::MessagingResponse.new
    response.message(body: message)
    return render xml: response.to_xml
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twilio/messages_helper.rb
module Twilio::MessagesHelper
end

app/views/clients/_form.html.erb
<div class="mt-5 container px-6 border border-primary rounded-sm col-8" style="background-color:#e6e6fa">
  <%= form_with model: Client, url: clients_path, remote: true do |form| %>
    <div class="form-group mt-3">
      <%= form.label :client_id %>
      <%= form.text_field :client_id, minlength: 32, maxlength: 32, required: true, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= form.label :client_secret %>
      <%= form.password_field :client_secret, minlength: 32, maxlength: 32, required: true, class: 'form-control' %>
    </div>
    <%= form.submit 'Submit', class: 'mb-3 btn btn-primary mb-4' %>
  <% end %>
</div>

app/views/clients/create.js.erb
<% if @client.errors.present? %>
  toastr.error('<%= @client.errors.full_messages.first %>');
<% else %>
  toastr.success('Client Added Successfully');
  window.location.href = "<%= root_path %>"
<% end %>

app/views/clients/new.html.erb
<%=render 'form' %>

app/views/home/index.html.erb
<div class="container">
  <h3 class="col-12 mt-4" style="font-family: monospace;">Follow these steps to setup your own SpotSearch</h3>
</div>
<div class="mt-2 container" style="background-color:#ffeeee;">
  <div class="card">
    <div class="col-12 p-4 pl-md-0" style="background-color:#dcdcdc;"> 
      <div class="ml-3 mr-2">
        <h5>
          STEP 1 - <%= link_to 'Create Your own Spotify APP', 'https://developer.spotify.com/dashboard/login', target: :_blank, class: "btn btn-primary btn-xl" %>
        </h5>
        <p>
          This will redirect you to Spotify Developer dashboard. Create you app by following steps mentioned on
          <br>
          <a href="https://sakshamjain16.medium.com/guide-to-set-up-your-own-whatsapp-bot-to-search-the-song-and-add-into-your-spotify-list-ead646a8b987">Medium Post</a>
          
        </p>
      </div>
    </div>
  </div>

    <div class="card"> 
      <div class="col-12 p-4 pl-md-0" style="background-color:#f0e68c;">
        <div class="ml-3 mr-2">
         <h5>STEP 2 - <%= link_to 'Add Your APP in SpotSearch', new_client_path, class: "btn btn-primary btn-xl" %></h5>
          <p>
            Till will open up a form where you need to enter your ClientId and ClientSecret 
          </p>
        </div>
      </div>
    </div>

    <div class="card"> 
      <div class="col-12 p-4 pl-md-0" style="background-color:#b6dec8;">
        <div class="ml-3 mr-2">
          <h5>STEP 3 - <%= link_to 'Sign in with Spotify', "#{@url}#{@param.to_query}", class: "btn btn-primary btn-xl" %></h5>
          <p>After filling form in STEP 2, click on this button to give SpotSearch permission to add songs in your Playlist</p>
        </div>
      </div>
    </div>
</div>
  

app/views/home/log_in.html.erb
Access_token: <%=@user.access_token %>
<hr>
Refresh_Token: <%= @user.refresh_token %>
<hr>
user_id: <%= @user.user_id %>
<hr>
code: <%= params[:code] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>